### ISSUE TITLE
sse.proxy.jwt error in zilla-examples/sse-server

### ISSUE THREAD

**Issue by vordimous** [aklivity/zilla-examples#92]
The error is in the https://github.com/jfallows/sse-server [code](https://github.com/jfallows/sse-server/blob/master/index.js#L36)

zilla-examples/sse-server:latest logs
```
2023-10-26 12:58:17 internal/process/esm_loader.js:74
2023-10-26 12:58:17     internalBinding('errors').triggerUncaughtException(
2023-10-26 12:58:17                               ^
2023-10-26 12:58:17 
2023-10-26 12:58:17 TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
2023-10-26 12:58:17     at Object.openSync (fs.js:454:10)
2023-10-26 12:58:17     at Object.readFileSync (fs.js:364:35)
2023-10-26 12:58:17     at SSEServer.createServer (file:///usr/app/node_modules/sse-server/index.js:36:15)
2023-10-26 12:58:17     at file:///usr/app/node_modules/sse-server/bin/cli.js:32:28
2023-10-26 12:58:17     at ModuleJob.run (internal/modules/esm/module_job.js:145:37)
2023-10-26 12:58:17     at async Loader.import (internal/modules/esm/loader.js:182:24)
2023-10-26 12:58:17     at async Object.loadESM (internal/process/esm_loader.js:68:5) {
2023-10-26 12:58:17   code: 'ERR_INVALID_ARG_TYPE'
2023-10-26 12:58:17 }
```

**Comment by vordimous** [comment]
The problem with the sse-sever stems from the [commit adding h2 suppor](https://github.com/jfallows/sse-server/commit/37489f759cabdbacdbe37903be56b18d66246331) which expects key and cert files but doesn't check for them not being available. The PR https://github.com/aklivity/zilla-examples/pull/94 will pull the sse-server code before that commit and allow the sse-server to work with this example.

**Comment by vordimous** [comment]
A different issue exists where the filesystem server can't serve the index.html file with the below error.

```
The webpage at https://localhost:9090/index.html might be temporarily down or it may have moved permanently to a new web address.
ERR_HTTP2_PROTOCOL_ERROR
```
